services:
  db:
    build: ./db
    image: db-frida
    container_name: db-container
    ports:
      - "3307:3306"
    env_file:
      - ./db/db.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend-frida
    restart: always

  api:
    build: "./"
    image: api-frida
    container_name: api-container
    ports:
      - "5000:5000"
    networks:
      - backend-frida
    restart: always
    depends_on:
      - db

volumes:
  db_data: {}

networks:
  backend-frida:
