services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: db-container
    environment:
        MYSQL_ROOT_PASSWORD: larces
    volumes:
        - ./db/entrypoint:/docker-entrypoint-initdb.d
    restart: always

  api:
    build: "./api"
    image: api
    container_name: api-container
    ports:
        - "80:80"
    restart: always
    depends_on:
        - db