"""empty message

Revision ID: a2b7c93ed2ae
Revises: 
Create Date: 2022-09-06 14:23:20.990957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2b7c93ed2ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id', table_name='sensitive_data')
    op.drop_table('sensitive_data')
    op.drop_index('email', table_name='appmeta')
    op.drop_table('appmeta')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appmeta',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=84), nullable=False),
    sa.Column('cpf', mysql.VARCHAR(length=86), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'appmeta', ['email'], unique=False)
    op.create_table('sensitive_data',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=84), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=84), nullable=False),
    sa.Column('cpf', mysql.VARCHAR(length=86), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'sensitive_data', ['user_id'], unique=False)
    # ### end Alembic commands ###


def upgrade_db2():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appmeta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=84), nullable=False),
    sa.Column('cpf', sa.String(length=86), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade_db2():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appmeta')
    # ### end Alembic commands ###


def upgrade_db3():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensitive_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=84), nullable=False),
    sa.Column('email', sa.String(length=84), nullable=False),
    sa.Column('cpf', sa.String(length=86), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade_db3():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensitive_data')
    # ### end Alembic commands ###


def upgrade_db4():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_db4():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

