"""empty message

Revision ID: a6fb53c24de2
Revises: 
Create Date: 2022-08-08 19:20:37.118037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6fb53c24de2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_0', sa.Integer(), nullable=True),
    sa.Column('_1', sa.Integer(), nullable=True),
    sa.Column('_2', sa.Integer(), nullable=True),
    sa.Column('_3', sa.Integer(), nullable=True),
    sa.Column('_4', sa.Integer(), nullable=True),
    sa.Column('_5', sa.Integer(), nullable=True),
    sa.Column('_6', sa.Integer(), nullable=True),
    sa.Column('_7', sa.Integer(), nullable=True),
    sa.Column('_8', sa.Integer(), nullable=True),
    sa.Column('_9', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###


def upgrade_db2():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_db2():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_db3():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_db3():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_db4():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_db4():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

